### ISSUE TITLE
"Attempt to map invalid URI" Error on Mac (M1)

### ISSUE THREAD

**Issue by NoahdoRegoUO** [DBraun/DawDreamer#128]
Here is an example of my code:

I render an engine, and attempt to make a plugin processor:

```
engine = daw.RenderEngine(SAMPLE_RATE, BUFFER_SIZE)

bass_boost = engine.make_plugin_processor("my_bass_boost", path.dirname(__file__)+conjoiner+'Plugins'+conjoiner+'PluginName.vst3')
```

However, I get the following error when trying to run the script (where [Path] represents my personal files):

```error: attempt to map invalid URI `/[Path]/Plugins/BarkOfDog2.vst3'```

I got the same error when running .dll which are Windows-only, so I switched to .vst3. I also noticed that the path is displaying with a backtick and a quotation, but I'm not sure how to fix that.

Is this error known / Am I missing something? I can provide more specific details if you'd like.

Thanks!

**Comment by CHEN-Manni** [comment]
I got the same error running .vst3 on Mac, then I try .vst it works...

**Comment by NoahdoRegoUO** [comment]
> I got the same error running .vst3 on Mac, then I try .vst it works...

Interesting, I'll try that- thanks for letting me know!

**Comment by CHEN-Manni** [comment]
> 

Files (vst instrument~)

**Comment by DBraun** [comment]
Sorry for the delay!

Fortunately I have an M1 too, so I see the same error. I think that the current files from Boz Digital Labs aren't compiled for M1.

```bash
otool -L /Library/Audio/Plug-Ins/VST/BarkOfDog2.vst/Contents/MacOS/BarkOfDog2
/Library/Audio/Plug-Ins/VST/BarkOfDog2.vst/Contents/MacOS/BarkOfDog2 (architecture x86_64):
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 12.0.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 136.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.0.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
/Library/Audio/Plug-Ins/VST/BarkOfDog2.vst/Contents/MacOS/BarkOfDog2 (architecture i386):
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 12.0.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 136.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.0.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
```

and for the vst3:

```bash
otool -L /Library/Audio/Plug-Ins/VST3/BarkOfDog2.vst3/Contents/MacOS/BarkOfDog2 
/Library/Audio/Plug-Ins/VST3/BarkOfDog2.vst3/Contents/MacOS/BarkOfDog2 (architecture x86_64):
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 17.0.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 153.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 52.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1138.23.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 41.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 635.15.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 53.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 833.20.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
/Library/Audio/Plug-Ins/VST3/BarkOfDog2.vst3/Contents/MacOS/BarkOfDog2 (architecture i386):
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 17.0.0)
	/System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 153.0.0)
	/usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 52.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 1138.23.0)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 41.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 635.15.0)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 53.0.0)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 833.20.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

We want to see something like `(architecture arm64)` or `(architecture arm64e)`

Do these plugins work in a DAW for you? I don't have Live installed on my mac right now.

This is what happens with DawDreamer for the vst3:
```
error: attempt to map invalid URI `/Library/Audio/Plug-Ins/VST3/BarkOfDog2.vst3'
```
but the vst error is more informative:
```bash
error: attempt to map invalid URI `/Library/Audio/Plug-Ins/VST/BarkOfDog2.vst'
Attempting to load VST: /Library/Audio/Plug-Ins/VST/BarkOfDog2.vst
2022-10-05 19:57:26.472 python[71755:6613614] Error loading /Library/Audio/Plug-Ins/VST/BarkOfDog2.vst/Contents/MacOS/BarkOfDog2:  dlopen(/Library/Audio/Plug-Ins/VST/BarkOfDog2.vst/Contents/MacOS/BarkOfDog2, 0x0106): tried: '/Library/Audio/Plug-Ins/VST/BarkOfDog2.vst/Contents/MacOS/BarkOfDog2' (fat file, but missing compatible architecture (have 'x86_64,i386', need 'arm64e'))
Traceback (most recent call last):
  File "/Users/admin/DawDreamer/tests/test_plugins.py", line 489, in <module>
    test_stereo_plugin_effect("/Library/Audio/Plug-Ins/VST/BarkOfDog2.vst")
  File "/Users/admin/DawDreamer/tests/test_plugins.py", line 19, in test_stereo_plugin_effect
    effect = engine.make_plugin_processor("effect", plugin_path)
```

**Comment by DBraun** [comment]
Closing due to seeing https://www.bozdigitallabs.com/the-great-plugin-rewrite-of-2022/
