### ISSUE TITLE
Error with x86 docker emulation under arm64

### ISSUE THREAD

**Issue by turian** [DBraun/DawDreamer#189]
```
joseph@Josephs-MacBook-Air ~/d/DawDreamer (main)> docker build  -t turian/dawdreamer .; docker stop dawdreamer ;  docker rm dawdreamer ; docker run -it --platform linux/amd64 --name dawdreamer turian/dawdreamer bash

[+] Building 0.9s (15/15) FINISHED                                                                    docker:desktop-linux
 => [internal] load .dockerignore                                                                                     0.0s
 => => transferring context: 2B                                                                                       0.0s
 => [internal] load build definition from Dockerfile                                                                  0.0s
 => => transferring dockerfile: 902B                                                                                  0.0s
 => [internal] load metadata for quay.io/pypa/manylinux2014_x86_64:latest                                             0.6s
 => [ 1/10] FROM quay.io/pypa/manylinux2014_x86_64@sha256:a96a8b62a98cd986f790c8b5ee6cd2846f96e7d22cca5e0d6db7ecb2e1  0.0s
 => [internal] load build context                                                                                     0.3s
 => => transferring context: 940.55kB                                                                                 0.3s
 => CACHED [ 2/10] RUN curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py" && python3.10 get-pip.py           0.0s
 => CACHED [ 3/10] COPY . /DawDreamer                                                                                 0.0s
 => CACHED [ 4/10] WORKDIR /DawDreamer/thirdparty/libfaust                                                            0.0s
 => CACHED [ 5/10] RUN sh download_libfaust.sh                                                                        0.0s
 => CACHED [ 6/10] WORKDIR /DawDreamer                                                                                0.0s
 => CACHED [ 7/10] RUN sh -v build_linux.sh                                                                           0.0s
 => CACHED [ 8/10] WORKDIR /DawDreamer                                                                                0.0s
 => CACHED [ 9/10] RUN python3.10 -m venv test-env                                                                    0.0s
 => CACHED [10/10] RUN /bin/bash -c "source test-env/bin/activate && pip install librosa scipy numpy pytest build wh  0.0s
 => exporting to image                                                                                                0.0s
 => => exporting layers                                                                                               0.0s
 => => writing image sha256:b10f2afd4e1a89f99e6b922a451e56fb910d3cd37d859b816d751f6bf83f244f                          0.0s
 => => naming to docker.io/turian/dawdreamer                                                                          0.0s

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview
dawdreamer
dawdreamer
[root@ec6fef47ac0e DawDreamer]# python
Python 2.7.5 (default, Nov 14 2023, 16:14:06)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import dawdreamer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dawdreamer/__init__.py", line 4, in <module>
    from .dawdreamer import *
ImportError: dawdreamer/dawdreamer.so: undefined symbol: PyInstanceMethod_Type
>
```

**Comment by turian** [comment]
Duplicate of #188
