### ISSUE TITLE
ImportError: DLL load failed while importing dawdreamer: The specified module could not be found.

### ISSUE THREAD

**Issue by dejawooh** [DBraun/DawDreamer#196]
Here are the steps to reproduce.

1. Install a fresh windows VM with below config
Device name	windows
Processor	Intel(R) Xeon(R) CPU @ 2.30GHz   2.30 GHz
Installed RAM	7.50 GB
System type	64-bit operating system, x64-based processor

2. Install python3.8 (tried with 3.10 and 3.12, same problem) --> 64bit
3. Install PyCharm IDE Community
4. Create a new project
5. Create + activate venv
6. pip install dawdreamer
`import platform print(platform.architecture())
`
`import dawdreamer as daw` 

```
('64bit', 'WindowsPE')
Traceback (most recent call last):
  File "C:\Users\deja\PycharmProjects\test\daw_test.py", line 23, in <module>
    import dawdreamer as daw
  File "C:\Users\deja\PycharmProjects\test\.venv\lib\site-packages\dawdreamer\__init__.py", line 4, in <module>
    from .dawdreamer import *
ImportError: DLL load failed while importing dawdreamer: The specified module could not be found.
```

Troubleshooting done so far:

1. Added Environment variables and restarted computer 
2. Added PYTHONPATH 
3. Added System Variable
4. Uninstalled and installed Python and dawdreamer several times
5. upgraded and downgraded dawdreamer several times
6. Used dependency walker took and found several red lines. 

Here's a picture of the dependency walker. I am using it for the first time so not sure if it helps. quick google search shows tons of results with similar error. tried several of those but none fixed the error I am getting. 

I have used linux and Mac OS all my life for coding so kind of new to windows environment. my apologies if this is something basic.

<img width="2220" alt="Screenshot 2024-03-28 at 6 30 39 AM" src="https://github.com/DBraun/DawDreamer/assets/9595168/62f6f51f-aebd-4853-8546-b61c8a498911">

**Comment by dejawooh** [comment]
@DBraun please let me know if you need any other info. happy to upload.

**Comment by dejawooh** [comment]
Found the solution
1. I had build a new windows VM and it was missing "Microsoft Visual C++ Redistributable package". 

All I had to do is to download this package from https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads (x64) version and install it. 

Now windows is able to find whatever files it needed.

Turned out be indeed a basic issue. 

Closing this.
